# Ambiente Ubuntu 26.04. Execute make nesta pasta.
# Os mesmos alvos do ambiente 22.04 são incluídos abaixo, sem copiar as receitas.
# CURDIR continua sendo esta pasta: chaves, downloads e results/ ficam separados.
VM_VERSION := 26.04
VM_TAG := 2604
VM_NAME := chen-ubuntu2604
VM_IP := 192.168.159.26
VM_NETWORK := chen-mgmt2604
VM_BRIDGE := virbr-chen26
VM_SUBNET := 192.168.159
VM_MAC := 52:54:00:ce:01:26
IMAGE_URL := https://cloud-images.ubuntu.com/releases/26.04/release
IMAGE_FILE := ubuntu-26.04-server-cloudimg-amd64.img

include ../vm-ubuntu2204/Makefile
